<a href="https://colab.research.google.com/github/BlackCerulean/Papaya-Classification/blob/main/Papaya_Recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Mount Google Drive
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
data_generator = ImageDataGenerator(
    rescale = 1. / 255, 
    shear_range = 0.2, 
    zoom_range = 0.2, 
    horizontal_flip = True,
    vertical_flip = True,
    rotation_range = 180,
    width_shift_range = 0.2,
    height_shift_range = 0.2,
    validation_split = 0.3) 

train_generator = data_generator.flow_from_directory(
    '/content/drive/MyDrive/Third Year/CSC340 Artificial Intelligent/Papaya Project/training', 
    target_size =(128, 128),
    batch_size=64,
    shuffle = True,
    class_mode = 'sparse',
    seed = 112,
    subset='training')

validation_generator = data_generator.flow_from_directory( 
    '/content/drive/MyDrive/Third Year/CSC340 Artificial Intelligent/Papaya Project/training', 
    target_size =(128, 128),
    batch_size=64,
    shuffle = True,
    class_mode = 'sparse',
    seed = 112,
    subset='validation')

# X_train, y_train = next(train_generator)
# X_test, y_test = next(validation_generator)

# print(train_generator)
# print(len(y_train))

Found 673 images belonging to 3 classes.
Found 286 images belonging to 3 classes.


In [ ]:
model = tf.keras.Sequential([

  tf.keras.layers.Conv2D(32, (3,3),padding='same', activation='relu', input_shape=(128,128, 3)),
  tf.keras.layers.MaxPooling2D((2,2),2), 
  tf.keras.layers.Conv2D(64, (3,3), padding='same', activation='relu'),
  tf.keras.layers.MaxPooling2D((2,2),2),
  
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(64, activation='relu'),
  tf.keras.layers.Dense(64, activation='relu'),

  tf.keras.layers.Dense(3, activation='softmax')
])

  # tf.keras.layers.Conv2D(128, (3,3), padding='same', activation='relu'),
  # tf.keras.layers.MaxPooling2D((2,2),2), 
  # tf.keras.layers.Conv2D(256, (3,3), padding='same', activation='relu'),
  # tf.keras.layers.MaxPooling2D((2,2),2),
  # tf.keras.layers.Conv2D(512, (3,3), padding='same', activation='relu'),
  # tf.keras.layers.MaxPooling2D((2,2),2),
  # tf.keras.layers.Conv2D(1024, (3,3), padding='same', activation='relu'),
  # tf.keras.layers.MaxPooling2D((2,2),2),
# tf.keras.layers.Conv2D(2048, (3,3), padding='same', activation='relu'),
# tf.keras.layers.MaxPooling2D((2,2),2),

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 128, 128, 32)      896       
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 64, 64, 32)       0         
 2D)                                                             
                                                                 
 conv2d_3 (Conv2D)           (None, 64, 64, 64)        18496     
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 32, 32, 64)       0         
 2D)                                                             
                                                                 
 conv2d_4 (Conv2D)           (None, 32, 32, 128)       73856     
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 16, 16, 128)     

In [ ]:
model.compile(optimizer='Adam',
              loss='sparse_categorical_crossentropy',
              metrics=["sparse_categorical_accuracy"])

In [ ]:
model.fit(train_generator, epochs=10, validation_data=validation_generator)

Epoch 1/10
11/11 [==============================] - 67s 6s/step - loss: 1.4160 - sparse_categorical_accuracy: 0.4383 - val_loss: 0.8962 - val_sparse_categorical_accuracy: 0.6049
Epoch 2/10
11/11 [==============================] - 64s 6s/step - loss: 0.6703 - sparse_categorical_accuracy: 0.7311 - val_loss: 0.9145 - val_sparse_categorical_accuracy: 0.5210
Epoch 3/10
11/11 [==============================] - 64s 6s/step - loss: 0.4070 - sparse_categorical_accuracy: 0.8425 - val_loss: 0.9354 - val_sparse_categorical_accuracy: 0.5874
Epoch 4/10
11/11 [==============================] - 64s 6s/step - loss: 0.4205 - sparse_categorical_accuracy: 0.8262 - val_loss: 0.8043 - val_sparse_categorical_accuracy: 0.6329
Epoch 5/10
11/11 [==============================] - 64s 6s/step - loss: 0.3531 - sparse_categorical_accuracy: 0.8514 - val_loss: 0.8033 - val_sparse_categorical_accuracy: 0.6329
Epoch 6/10
11/11 [==============================] - 64s 6s/step - loss: 0.3485 - sparse_categorical_accuracy: 

In [ ]:
filePath = '/content/drive/MyDrive/Third Year/CSC340 Artificial Intelligent/Papaya Project/'

In [ ]:
# Save Model
# model.save(filePath+'Model/papayaV6.h5')

In [ ]:
model = tf.keras.models.load_model(filePath+'Model/papayaV5.h5')

In [ ]:
def translate(x):
    return {
        0: 'ripe',
        1: 'medium',
        2: 'unripe',
        3: 'error'
    }.get(x, 3)



In [ ]:
path = filePath+'predict/MicrosoftTeams-image (1).png'
# path = '/content/papaya06.png'
img = image.load_img(path, target_size=(128, 128, 3))
x = image.img_to_array(img) / 255.0
x = np.expand_dims(x, axis=0)
images = np.vstack([x])
classes = model.predict(images)
# score = tf.nn.softmax(classes[0])
print("Status: ", translate(np.argmax(classes[0])))
print("Confident Level: ", np.max(classes[0])*100)

Status:  unripe
Confident Level:  68.41087937355042


In [ ]:
path = filePath + 'predict/papaya02.jpg'
img = image.load_img(path, target_size=(128,128,3))
x = image.img_to_array(img) / 255.0
x = x.reshape(1,128,128,3)
classes = model.predict(x)
print(classes)
print("Status: ", translate(np.argmax(classes[0])))
print("Confident Level: ", np.max(classes[0])*100)

# f = os.path.join(filePath+'predict/Test', filename)
# img = image.load_img(f, target_size=(128, 128, 3))
# x = image.img_to_array(img)/ 255.0
# x = np.expand_dims(x, axis=0)
# images = np.vstack([x])
# img = cv2.imread(f)
# img = image.img_to_array(img)
# img = cv2.resize(img,(128,128))
# img = img / 255.
# img = img.reshape(128,128,3)
# img = np.expand_dims(img, axis=0)

[[6.8690020e-01 3.1308550e-01 1.4263943e-05]]
Status:  ripe
Confident Level:  68.69001984596252


In [ ]:
import cv2
import os

x_predict = []
for filename in os.listdir(filePath+'predict/Test'):
  f = os.path.join(filePath+'predict/Test', filename)
  img = image.load_img(f, target_size=(128,128,3))
  x = image.img_to_array(img) / 255.0
  x = x.reshape(1,128,128,3)
  classes = model.predict(x)
  print(np.max(classes[0]), translate(np.argmax(classes[0])))
  x_predict.append(translate(np.argmax(classes[0])))


0.528332 medium
0.73420525 medium
0.9718401 unripe
0.9809141 medium
0.915578 unripe
0.9053623 ripe
0.97597903 medium
0.7608648 medium
0.50944877 ripe
0.9724361 ripe
0.94291484 ripe
0.9624167 medium
0.6177479 medium
0.83332413 medium
0.70780087 medium
0.9162252 unripe
0.8963288 unripe
0.7611853 unripe
0.644095 ripe
0.64797693 medium
0.91812634 unripe
0.9454306 medium
0.7542327 medium
0.7753365 unripe
0.91856664 unripe
0.942022 unripe
0.71256286 medium
0.5374842 ripe
0.8865002 unripe
0.9131057 ripe
0.85602546 ripe
0.95319813 unripe
0.8903623 unripe
0.9547739 unripe
0.9744828 medium
0.51376647 unripe
0.776585 medium
0.74982756 medium
0.8781089 unripe
0.97079426 unripe
0.98179376 unripe
0.960844 medium
0.91191685 ripe
0.87672853 unripe
0.97223186 unripe
0.9822499 unripe
0.9506398 ripe
0.72647655 medium
0.96698016 ripe
0.63732845 ripe
0.84828275 medium
0.8495325 unripe
0.8591796 unripe
0.94096744 unripe
0.9493533 unripe
0.51103354 unripe
0.84248537 unripe
0.90422547 unripe
0.6588709 ripe
0.

In [ ]:
# Confusion matrix
from sklearn import metrics
import pandas as pd

x_actual = pd.read_csv(filePath+'Model/newResult.csv', header = None)
print(metrics.confusion_matrix(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))
print(metrics.classification_report(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))

[[16 12  0]
 [ 1 24  2]
 [ 0  2 43]]
              precision    recall  f1-score   support

        ripe       0.94      0.57      0.71        28
      medium       0.63      0.89      0.74        27
      unripe       0.96      0.96      0.96        45

    accuracy                           0.83       100
   macro avg       0.84      0.81      0.80       100
weighted avg       0.86      0.83      0.83       100



In [ ]:
# Confusion matrix V2
from sklearn import metrics
import pandas as pd

x_actual = pd.read_csv(filePath+'Model/newResult.csv', header = None)
print(metrics.confusion_matrix(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))
print(metrics.classification_report(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))

[[16 12  0]
 [ 0 26  1]
 [ 0  6 39]]
              precision    recall  f1-score   support

        ripe       1.00      0.57      0.73        28
      medium       0.59      0.96      0.73        27
      unripe       0.97      0.87      0.92        45

    accuracy                           0.81       100
   macro avg       0.86      0.80      0.79       100
weighted avg       0.88      0.81      0.81       100



In [ ]:
# Confusion matrix V3
from sklearn import metrics
import pandas as pd

x_actual = pd.read_csv(filePath+'Model/newResult.csv', header = None)
print(metrics.confusion_matrix(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))
print(metrics.classification_report(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))

[[15 13  0]
 [ 1 24  2]
 [ 0  2 43]]
              precision    recall  f1-score   support

        ripe       0.94      0.54      0.68        28
      medium       0.62      0.89      0.73        27
      unripe       0.96      0.96      0.96        45

    accuracy                           0.82       100
   macro avg       0.84      0.79      0.79       100
weighted avg       0.86      0.82      0.82       100



In [ ]:
# Confusion matrix V4
from sklearn import metrics
import pandas as pd

x_actual = pd.read_csv(filePath+'Model/newResult.csv', header = None)
print(metrics.confusion_matrix(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))
print(metrics.classification_report(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))

[[15 13  0]
 [ 1 25  1]
 [ 0  1 44]]
              precision    recall  f1-score   support

        ripe       0.94      0.54      0.68        28
      medium       0.64      0.93      0.76        27
      unripe       0.98      0.98      0.98        45

    accuracy                           0.84       100
   macro avg       0.85      0.81      0.81       100
weighted avg       0.88      0.84      0.84       100



In [ ]:
# Confusion matrix V5
from sklearn import metrics
import pandas as pd

x_actual = pd.read_csv(filePath+'Model/newResult.csv', header = None)
print(metrics.confusion_matrix(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))
print(metrics.classification_report(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))

[[23  5  0]
 [ 1 23  3]
 [ 0  0 45]]
              precision    recall  f1-score   support

        ripe       0.96      0.82      0.88        28
      medium       0.82      0.85      0.84        27
      unripe       0.94      1.00      0.97        45

    accuracy                           0.91       100
   macro avg       0.91      0.89      0.90       100
weighted avg       0.91      0.91      0.91       100



In [ ]:
# Confusion matrix V6
from sklearn import metrics
import pandas as pd

x_actual = pd.read_csv(filePath+'Model/newResult.csv', header = None)
print(metrics.confusion_matrix(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))
print(metrics.classification_report(x_actual, x_predict, labels=['ripe', 'medium', 'unripe']))

[[18 10  0]
 [ 2 24  1]
 [ 0  1 44]]
              precision    recall  f1-score   support

        ripe       0.90      0.64      0.75        28
      medium       0.69      0.89      0.77        27
      unripe       0.98      0.98      0.98        45

    accuracy                           0.86       100
   macro avg       0.85      0.84      0.83       100
weighted avg       0.88      0.86      0.86       100

